### ISSUE TITLE
Recursive mapping

### ISSUE THREAD

**Issue by valnoc** [Yalantis/FastEasyMapping#53]
Hi! Thx for your work on FEM.

I have faced a problem with one case. Let's say, we have entity with a relationship to self.
```
TreeNode {
id - nsnumber
name - nsstring
children - nsset<TreeNode>
}
```
I define mapping, as it was recommended - having a defaultMapping method, which returns FEMMapping.
And I have an infinite recursion, because inside defautlMapping I call this method again to get mapping for children property.
And of course, I'm talking about a general situation - when number of tree levels are not defined or  known while developing an app.

Any ideas, how to handle this?
Or, maybe, any ideas about what kind of changes should I do in FEM to make fork / pull request?

**Comment by dimazen** [comment]
Hi, @valnoc! Thanks for the usage :) 

Unfortunately this feature isn't supported yet.

**Comment by LivioGama** [comment]
I had this situation in a project.
Let's say that you have an entity User that have followers (like in Twitter) which are users themselves.
Instead of having a relationship "followers" to User itself, make and attribute "followers_uuids" Transformable where you will store and NSArray<NSString *> *followersUUID.

In your parsing, you still parse and store all the Users, but in you code, in order to get followers you can do :
let myFollowers = User.MR_findAllWithPredicate(NSPredicate("uuid IN %@", currentUser.followers_uuids)

**Comment by valnoc** [comment]
Thx for the responses!

@dimazen 
ok) i'll try to dive into FEM a little bit later and add this case (if it could be done without a lot of pain).
Do not close this issue, please.

@LivioGama 
I came up with a similar solution. 
I create another mapping for children objects, which uses only identifiers. All children are preliminarily added to the JSON root collection to get all the info mapped.
As far as i use CoreData - all fetched treeNodes come with full children entities.

**Comment by dimazen** [comment]
Merged by https://github.com/Yalantis/FastEasyMapping/pull/68
