### ISSUE TITLE
Comparison to ObjectMapper swift

### ISSUE THREAD

**Issue by Maxatma** [Yalantis/FastEasyMapping#77]
Hi, any library comparison to this one https://github.com/Hearst-DD/ObjectMapper ?

**Comment by dimazen** [comment]
@Maxatma Hello there. Let me take a look at the internals of the ObjectMapper. I'll get back to you shortly.

**Comment by dimazen** [comment]
@Maxatma I reviewed ObjectMapping as here is sort of small comparison: 

- FEM is built on top of the KVC. As the result you can work only with `NSObject` successors. Also you're loosing type safety if you're working in Swift. ObjectMapper in contrast done with Swift in mind, therefore you're able to work with `struct` or any Swift `class` without pain. 

I would say that FEM was done mostly for the CoreData mapping. ObjectMapper doesn't seem to handle CoreData in any way out of the box. FEM in contrast manages pre-fetching to speed up CoreData mapping. 

So if you're looking for CoreData mapping that needs to be fast - I'd suggest to use FEM. Otherwise ObjectMapper seems to be better for the pure Swift project :)

**Comment by Maxatma** [comment]
@dimazen Thanks for your time. I'm just looking for update my objc project, I have used FEM for mapping my Realm objects before, it provide really cool and simple syntax. 
ObjectMapper has a lot of  
something    <- map["something"] 
this kind of code. And it looks like I can't avoid it.

**Comment by dimazen** [comment]
I'm not sure that there are any mappings on pure swift that provides same syntax as FEM due to absence of the KVC. :(

**Comment by Maxatma** [comment]
@dimazen Okay and Thanks again :)

**Comment by dimazen** [comment]
You're welcome!
